
package gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import logicaComunicaciones.ProtocolEventListener;
import logicaComunicaciones.ProtocolEventObject;
import logicaWorkFlow.Tarea;
import logicaWorkFlow.WorkFlowEventListener;
import logicaWorkFlow.WorkFlowEventObject;
import main.TF4SM;

/**
 * Clase que pinta y permite interactuar con la aplicación 
 * para el guante
 * 
 * @author Borja Bordel
 * @date Mayo 2015
 */
public class AppGuante extends javax.swing.JFrame implements ProtocolEventListener, WorkFlowEventListener {

    /**
     * Constructor
     * Creates new form AppGuante
     */
    public AppGuante() {
        initComponents();
        sistema = TF4SM.getSistema();
        String puertoGuante = JOptionPane.showInputDialog(this, "Introduzca el puerto en el que está conectado el guante", null);
        sistema.cambiaPuertos(null, puertoGuante);
        sistema.iniciaComunicacionGuante();
        sistema.addProtocolEventListener(this);
        sistema.addWorkFlowEventListener(this);
        estadoActual.setText("no sostiene ningún objeto");
        lastTarea = 0;
        
        numeros [0]= numero0;
        numeros [1] = numero1;
        numeros [2] = numero2;
        
        nombres [0]= nombre0;
        nombres [1] = nombre1;
        nombres [2] = nombre2;
        
        estados [0]= estado0;
        estados [1] = estado1;
        estados [2] = estado2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        cuadroNumero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        estadoActual = new javax.swing.JLabel();
        mensaje2 = new javax.swing.JLabel();
        mensaje3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        numero0 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numero1 = new javax.swing.JLabel();
        nombre0 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        estado2 = new javax.swing.JLabel();
        numero2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        estado1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estado0 = new javax.swing.JLabel();
        cuadroNumeroTarea = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        mensaje4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mensaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mensaje1.setText("Ver últimas trazas del objeto...");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mensaje.setText("Ahora mismo el guante...");

        estadoActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(estadoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mensaje)
                .addGap(18, 18, 18)
                .addComponent(estadoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mensaje2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mensaje2.setText("ESTADO ACTUAL DEL SISTEMA");

        mensaje3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mensaje3.setText("TAREAS DEFINIDAS");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numero0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Número");

        numero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nombre0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Estado");

        nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        estado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        numero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        estado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");

        estado0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(nombre0, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(estado0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(numero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(numero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(estado2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero0, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                    .addComponent(nombre0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estado0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mensaje4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mensaje4.setText("Ejecutar desde tarea...");

        jButton3.setText("Ejecutar las tareas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Definir una nueva tarea");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Borrar tareas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(mensaje2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje3)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mensaje1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cuadroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cuadroNumeroTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje2)
                    .addComponent(mensaje3))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensaje1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuadroNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensaje4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuadroNumeroTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    /**
     * Llama al sistema de obtención y escritura de trazas para un objeto dado
     * @param evt Evento
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (cuadroNumero.getText().equals("")) {
             JOptionPane.showMessageDialog(null, "Debe indicar un número de objeto", "Falta información", JOptionPane.WARNING_MESSAGE);
        } else {
            String [] args = {cuadroNumero.getText()};
            LienzoTrazas.main (args);
        }
    }                                        
    
    /**
     * Función de cierre para los puertos
     * 
     * @param evt Evento 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        sistema.cierraComunicacion();
    }                                  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String dato = cuadroNumeroTarea.getText();
        if (dato.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe indicar un número de tarea", "Falta información", JOptionPane.WARNING_MESSAGE);
        } else {
            int seleccion = JOptionPane.showConfirmDialog(null, "A partir de este momento todas las interacciones se consideran parte de las tareas", 
                                                      "Confirme selección", JOptionPane.OK_CANCEL_OPTION);
            if (seleccion == JOptionPane.OK_OPTION) {
                int numTarea = Integer.parseInt(dato);
                if (!sistema.ejecutaDesdeTarea(numTarea)) {
                    JOptionPane.showMessageDialog(null, "Debe indicar el número de una tarea definida", "Error en el número de tarea", JOptionPane.WARNING_MESSAGE);
                } else {
                    int n = (int)(lastTarea/numeros.length);
                    for (int i = n*numeros.length ;  i < lastTarea ; i++) {
                        if (i >= numTarea) {estados[i].setText(Tarea.ESTADO_PENDIENTE);}
                    }                    
                    sistema.ActivaWorkFlow();
                    estados[numTarea].setText(Tarea.ESTADO_EJECUTANDO);
                }
            }            
        }
    }                                        
    
    /**
     * Evento de inicio de WorkFlow
     * 
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int seleccion = JOptionPane.showConfirmDialog(null, "A partir de este momento todas las interacciones se consideran parte de las tareas", 
                                                      "Confirme selección", JOptionPane.OK_CANCEL_OPTION);
        if (seleccion == JOptionPane.OK_OPTION) {
            sistema.reiniciaWorkFlow();
            int n = (int)(lastTarea/numeros.length);            
            for (int i = n*numeros.length ;  i < lastTarea ; i++) {
                estados[i].setText(Tarea.ESTADO_PENDIENTE);
            }
            sistema.ActivaWorkFlow();
            estados[0].setText(Tarea.ESTADO_EJECUTANDO);
        }
    }                                        
    
    /**
     * Evento de creación de una nueva tarea
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        FormularioTarea.main(null);
    }                                        
    
    /**
     * Evento de borrado de tareas
     * 
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        sistema.borraWorkFlow();
        lastTarea = 0;
        for (JLabel nombre : nombres) {
            nombre.setText("");
        }
        for (JLabel numero : numeros) {
            numero.setText("");
        }
        for (JLabel estado : estados) {
            estado.setText("");
        }
    }                                        

    /**
     * Método main
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGuante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGuante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGuante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGuante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGuante().setVisible(true);
            }
        });
    }
    
    /**
     * Cambia el estado del guante mostrado en 
     * pantalla
     * 
     * @param args Evento que dispara el método
     */
    public void cambiaEstado (ProtocolEventObject args) {
        if (args.getValidez() == false) {
            JOptionPane.showMessageDialog(null, args.getMensaje(), "Error de lectura", JOptionPane.WARNING_MESSAGE);
        } else {
            String linea;
            if (args.getNumObjeto() == 0) {
                linea = "no sostiene ningún objeto";
            } else {
                if (args.getNumObjeto() == -1) {
                    linea = "sostiene un objeto desconocido";
                } else {
                    linea = "sostiene el objeto "+args.getNumObjeto();
                }                
            }
            estadoActual.setText(linea);
        }        
    }
    
    /**
     * Evento que actualiza el estado de la tareas y modifica la visualización 
     * por pantalla
     * 
     * @param event 
     */
    public void actualizaTareas (WorkFlowEventObject event) {
        if (event.IsNueva()) {
            numeros[lastTarea%numeros.length].setText(String.valueOf(event.getTarea().getNumero()));
            nombres[lastTarea%numeros.length].setText(event.getTarea().getNombre());
            estados[lastTarea%numeros.length].setText(event.getTarea().getEstado());
            lastTarea++;
        } else {
            int n = (int)(lastTarea/numeros.length);
            if (event.getTarea().getNumero() >= n*numeros.length && event.getTarea().getNumero() <= (n+1)*numeros.length-1) {
                estados[event.getTarea().getNumero()].setText(event.getTarea().getEstado());
            } 
            if(!event.getTarea().IsExitosa()) {
                JOptionPane.showMessageDialog(null, "Una de las tareas ha fallado","Fallo en una tarea", JOptionPane.WARNING_MESSAGE);               
                sistema.DesactivaWorkFlow();  
            } else {
                if (event.IsFisnished()) {
                    JOptionPane.showMessageDialog(null, "Todas las tareas han sido ya evaluadas", "Ejecuación finalizada", JOptionPane.INFORMATION_MESSAGE);
                    sistema.DesactivaWorkFlow(); 
                } else {
                    estados[event.getTarea().getNumero()+1].setText(Tarea.ESTADO_EJECUTANDO);
                }
            }
        }
    }
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JTextField cuadroNumero;
    private javax.swing.JTextField cuadroNumeroTarea;
    private javax.swing.JLabel estado0;
    private javax.swing.JLabel estado1;
    private javax.swing.JLabel estado2;
    private javax.swing.JLabel estadoActual;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    private javax.swing.JLabel mensaje4;
    private javax.swing.JLabel nombre0;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel numero0;
    private javax.swing.JLabel numero1;
    private javax.swing.JLabel numero2;
    // End of variables declaration                   
    private TF4SM sistema;
    private JLabel [] numeros = new JLabel [3];
    private JLabel [] nombres = new JLabel [3];
    private JLabel [] estados = new JLabel [3];
    int lastTarea;
}
