package gui;

import javax.swing.JOptionPane;
import main.TF4SM;

/**
 * Clase que contiene y crea un nuevo formulario para
 * introducir una nueva tarea al sistema
 * 
 * @author Borja Bordel Sánchez
 * @date Julio 2015
 */
public class FormularioTarea extends javax.swing.JFrame {

    /**
     * Constructor
     */
    public FormularioTarea() {
        initComponents();
        sistema = TF4SM.getSistema();
        numero.setText(sistema.getNumeroTareaSiguiente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Mensaje = new javax.swing.JLabel();
        Mensaje1 = new javax.swing.JLabel();
        Mensaje2 = new javax.swing.JLabel();
        cuadroNombre = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        Mensaje3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroDescripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Mensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje.setText("DEFINIR UNA NUEVA TAREA");

        Mensaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje1.setText("Tarea número:");

        Mensaje2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje2.setText("Nombre:");

        cuadroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroNombreActionPerformed(evt);
            }
        });

        Mensaje3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje3.setText("Descripción:");

        cuadroDescripcion.setColumns(20);
        cuadroDescripcion.setRows(5);
        jScrollPane1.setViewportView(cuadroDescripcion);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Mensaje1)
                            .addGap(18, 18, 18)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(Mensaje))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Mensaje2)
                            .addGap(55, 55, 55)
                            .addComponent(cuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Mensaje3)
                        .addComponent(jScrollPane1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Mensaje)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mensaje1)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mensaje2)
                    .addComponent(cuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Mensaje3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    /**
     * Evento de cierre de ventana
     * 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
    }                                        
    
    /**
     * Evento sin ejecuación
     * 
     * @param evt 
     */
    private void cuadroNombreActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
    }                                            
    
    /**
     * Evento de creación de la tarea
     * 
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String nombre = cuadroNombre.getText();
        String descripcion = cuadroDescripcion.getText();
        
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe escribir un nombre de tarea", "Falta información", JOptionPane.WARNING_MESSAGE);
        } else {
            if (!sistema.validarTarea(descripcion)) {
                JOptionPane.showMessageDialog(null, "Alguna sentencia de la descripción no se reconoce", "Error en WorkFlow", JOptionPane.WARNING_MESSAGE);
            } else {
                sistema.procesaTarea(descripcion, nombre);
                this.setVisible(false);
            }
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel Mensaje1;
    private javax.swing.JLabel Mensaje2;
    private javax.swing.JLabel Mensaje3;
    private javax.swing.JTextArea cuadroDescripcion;
    private javax.swing.JTextField cuadroNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numero;
    // End of variables declaration                   
    private TF4SM sistema;
}
