
package gui;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.BaseDatos;


/**
 * Clase de inicio de la interfaz gráfica
 * 
 * @author Borja Bordel
 * @date Mayo 2015
 */
public class InicioGUI extends javax.swing.JFrame {

    /**
     * Constructor
     * Creates new form Inicio
     */
    public InicioGUI() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Mensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        balda = new javax.swing.JRadioButton();
        guante = new javax.swing.JRadioButton();
        Mensaje1 = new javax.swing.JLabel();
        textoInventario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Mensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje.setText("Seleccione el archivo de inventario de sus productos");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        balda.setText("Balda");

        guante.setText("Guante");
        guante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guanteActionPerformed(evt);
            }
        });

        Mensaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje1.setText("Escoja los elementos que forman su sistema");

        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mensaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(guante)
                .addGap(78, 78, 78)
                .addComponent(balda)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(textoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Mensaje1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guante)
                    .addComponent(balda))
                .addGap(33, 33, 33)
                .addComponent(Mensaje)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    
    /**
     * Comienza la monitorización de los objetos
     * inteligentes.
     * Carga el listado de productos y abre la plataforma de visualización
     * 
     * @param evt Evento
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       boolean g_state = guante.isSelected();
       boolean b_state = balda.isSelected();
       
       // LECTURA DEL INVENTARIO EN UN TEXT
       String pathInventario = textoInventario.getText();
       if (pathInventario == null) {
           JOptionPane.showMessageDialog(null, "Debe seleccionar un listado de productos", 
                   "Falta información", JOptionPane.WARNING_MESSAGE);
           return;
       } else{ 
           int index = pathInventario.lastIndexOf('.');            
           if (index == -1 || !pathInventario.substring(index + 1).equalsIgnoreCase("txt")) {
               JOptionPane.showMessageDialog(null, "El formato del listado de productos no es correcto", 
                       "Error en listado", JOptionPane.WARNING_MESSAGE);
                return;
           } else {
               try {
                   BaseDatos.inicializa(new File(pathInventario));
               } catch (Exception ex) {
                   JOptionPane.showMessageDialog(null, "Error al cargar el fichero de productos", 
                           "Error en listado", JOptionPane.ERROR_MESSAGE);
                   return;
               }
           }           
       }
       
       if (g_state == true) {;
           if(b_state == true) {
               AppBaldaGuante.main(null);
           } else {
               AppGuante.main(null);
           }
       } else if (b_state == true) {
           AppBalda.main(null);
       } else {
           JOptionPane.showMessageDialog(null, "Debe seleccionar algún elemento", "Falta información", JOptionPane.WARNING_MESSAGE);
           return;
       } 
       
       this.setVisible(false);
    }                                        
  
    //sin uso
    private void guanteActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
    
    /**
     * Función de cierre para evitar que queden recursos
     * descolgados
     * 
     * @param evt Eventos que generan 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
    }                                  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         JFileChooser fc = new JFileChooser();
         int seleccion= fc.showOpenDialog(this);
         if(seleccion == JFileChooser.APPROVE_OPTION){             
            //Ecribe la ruta del fichero seleccionado en el campo de texto
            textoInventario.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }                                        

    /**
     * Método main
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioGUI().setVisible(true);                
            }
        });
    }  

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel Mensaje1;
    private javax.swing.JRadioButton balda;
    private javax.swing.JRadioButton guante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField textoInventario;
    // End of variables declaration                   
}
